version: 'python:3.11'

services:
  web:  # Убедитесь, что это имя сервиса, которое вы будете использовать
    build:
      context: .  # Убедитесь, что Dockerfile находится в текущем контексте
      dockerfile: Dockerfile  # Убедитесь, что указано имя вашего Dockerfile
    ports:
      - "5000:5000"  # Связываем порт контейнера с портом хоста
    restart: unless-stopped  # Перезапуск контейнера в случае его завершения
