#!/bin/bash

# Остановить текущий контейнер
if [ "$(docker ps -q -f name=flask_web_1)" ]; then
    echo "Stopping the flask_web container..."
    docker stop flask_web_1 || true
fi

# Удалить текущий контейнер
if [ "$(docker ps -aq -f status=exited -f name=flask_web_1)" ]; then
    echo "Removing the flask_web container..."
    docker rm flask_web_1 || true
fi

# Пересобрать и запустить образ с помощью docker-compose
echo "Building and starting the container..."
docker-compose up -d --build

echo "Flask приложение обновлено и доступно по адресу http://localhost:5000"
